name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - mediawiki/**
  pull_request:
    branches: [ "main" ]
    paths:
      - mediawiki/**

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file mediawiki/Dockerfile --tag sca-rules-wiki:$(date +%s)
     
