# MediaWiki with MySQL
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
services:
  mediawiki:
    depends_on:
      database:
        condition: service_healthy
        restart: true
    image: sca-rules-wiki:latest
    environment:
      - SITE_NAME=${SITE_NAME}
      - BASE_URL=${BASE_URL}
      - WIKI_EMAIL=${WIKI_EMAIL}
      - DB_URL=database:3306
      - DB_NAME=mediawiki
      - DB_USER=mediawiki
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_SECRET_KEY=${DB_SECRET_KEY}
      - DB_UPGRADE_KEY=${DB_UPGRADE_KEY}
    restart: always
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${CONTEXT_DIRECTORY}/images
        target: /var/www/html/images
        read_only: false
      - type: bind
        source: ${CONTEXT_DIRECTORY}/LocalSettings.php
        target: /var/www/html/LocalSettings.php
        read_only: true
      
  database:
    image: sca-rules-db:latest
    # image: mysql:8.4.0
    environment:
      - DB_NAME=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - BACKUPS_LOCATION=/docker-entrypoint-initdb.d/
    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    volumes:
      - type: bind
        source: ${CONTEXT_DIRECTORY}/db_backups
        target: /db_backups
        read_only: false
